RUN_CMD = 1
CAL_CMD = 2
SETFREQ_CMD = 3
HOUSEKEEPING_CMD = 4
POWER_CMD = 5
DIAG_CMD = 6
ADMIN_CMD = 7

RUN_HEADER_SIZE = 10
RUN_ARM_SIZE = 14
CAL_HEADER_SIZE = 8
CAL_ARM_SIZE = 10
SETFREQ_HEADER_SIZE = 8
SETFREQ_ARM_SIZE = 6
HOUSEKEEPING_HEADER_SIZE = 8
POWER_HEADER_SIZE = 8
DIAG_HEADER_SIZE = 6
ADMIN_HEADER_SIZE = 8

cmds = {RUN_CMD:(RUN_HEADER_SIZE, RUN_ARM_SIZE),
        CAL_CMD:(CAL_HEADER_SIZE, CAL_ARM_SIZE),
        SETFREQ_CMD:(SETFREQ_HEADER_SIZE, SETFREQ_ARM_SIZE),
        HOUSEKEEPING_CMD:(HOUSEKEEPING_HEADER_SIZE, 0),
        POWER_CMD:(POWER_HEADER_SIZE, 0),
        DIAG_CMD:(DIAG_HEADER_SIZE, 0),
        ADMIN_CMD:(ADMIN_HEADER_SIZE, 0)}
